// <auto-generated />
namespace class_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class newtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newtable));
        
        string IMigrationMetadata.Id
        {
            get { return "202201100931110_newtable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
